# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 643b2b47903da65fcbe39a58c8ed0d6ecb93ab40e18031c86bd9e765e04c8c585a044ffc9e88ff47040352f0bbcdbaa382d6dedf58205565d35fd90e1aa3db15

test:
  secret_key_base: f1400665dc22b652953d921ec240d2027097e0c7402c76a702684c66d44e87407fbdc54ebb5827b5e24dd4e93f41bcc40c76cc7132a23bae298e9ef433caee12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
